#!/bin/bash
PGM_BIN=spx
PGM_VERSION=0.1.3

find_data_dir() {
    local cwd=$(pwd)

    while [ $cwd != "/" ]; do
        local dir="$cwd/.spx"
        if [ -d "$dir" ]; then
            echo "$dir"
            return
        fi
        cwd=$(dirname "$cwd")
    done
}

# No command found
if [ -z "$1" ]; then
    echo "usage $PGM_BIN [--version] <command> [<args>]"
    exit 0
fi

case "$1" in
    -v|--version)
        echo "Sphex version $PGM_VERSION"
        exit 0
        ;;
esac

_sub_cmd=$1
shift

# Environment defined data dir
if [ -n "$SPHEX_DIR" ]; then
    if [[ "$_sub_cmd" == "init" || -d "$SPHEX_DIR" ]]; then
        DATA_DIR=$SPHEX_DIR
    else
        echo "SPHEX_DIR not found: \"$SPHEX_DIR\"."
        exit 1
    fi

# Find data dir
else
    if [ "$_sub_cmd" == "init" ]; then
        DATA_DIR="$(pwd)/.spx"
    else
        DATA_DIR=$(find_data_dir)
        if [ -z "$DATA_DIR" ]; then
            echo "No repository found. Use \"$PGM_BIN init\""
            exit 1
        fi
    fi
fi


# Check to see if sub-command is in path
_sub_bin="$PGM_BIN-$_sub_cmd"
_fullpath_sub_bin=$(which "$_sub_bin" 2> /dev/null)
if [ $? -ne 0 ]; then
    # else .. Look at the location where this command is
    _fullpath_sub_bin="$(dirname $(realpath $0))/$_sub_bin"
    if [ ! -x "$_fullpath_sub_bin" ]; then
        echo "Invalid command $_fullpath_sub_bin."
        exit 1
    fi
fi


# Execute command
(
export PGM_BIN
export DATA_DIR
$_fullpath_sub_bin "$@"
)
