#!/bin/bash
PGM_BIN=spx
PGM_VERSION=0.1.2

# TODO(jfrias): determine dir
DATA_DIR=.spx

# No command found
if [ -z "$1" ]; then
    echo "usage $PGM_BIN [--version] <command> [<args>]"
    exit 0
fi

while (( "$#" )); do
    case "$1" in
        -v|--version)
            echo "Sphex version $PGM_VERSION"
            exit 0
            ;;
        *)
            _params="$_params $1"
            shift
            ;;
    esac
done

eval set -- "$_params"

# Look in the current directory
_cwd=$(pwd)
if [ -x "$_cwd/$PGM_BIN-$1" ]; then
    cmd="$_cwd/$PGM_BIN-$1"

# Look in the parth
else
    cmd=$(which "$PGM_BIN-$1" 2> /dev/null)
    if [[ $? -ne 0 || ! -x "$cmd" ]]; then
        echo "Invalid command $1."
        exit 1
    fi
fi

# Execute command
shift
(
export PGM_BIN
export DATA_DIR
$cmd $*
)
