#!/bin/bash

INSTALL_DIR=$(dirname $(realpath "$0"))
source "$INSTALL_DIR/spx-core"

usage() {
    cat <<-EOF
Sphex v$PGM_VERSION - Version control system

Usage: $PGM_BIN [-h] [-v] <command>

Options:
    -h, --help     Show help
    -v, --version  Show version and quit

Commands:
    init  Initialize a repository
    ci    Check-in file
    co    Check-out file
    log   Display file history
EOF
}

find_data_dir() {
    local cwd=$(pwd)

    while [ $cwd != "/" ]; do
        local dir="$cwd/.spx"
        if [ -d "$dir" ]; then
            echo "$dir"
            return
        fi
        cwd=$(dirname "$cwd")
    done
}

# No command found
if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
    usage
    exit 0
fi

case "$1" in
    -v|--version)
        echo "Sphex version $PGM_VERSION"
        exit 0
        ;;
    -*|--*=)
        echo "Unsupported flag $1." >&2
        exit 1
        ;;
esac

_sub_cmd=$1
shift

# Environment defined data dir
if [ -n "$SPHEX_DIR" ]; then
    if [[ "$_sub_cmd" == "init" || -d "$SPHEX_DIR" ]]; then
        DATA_DIR=$SPHEX_DIR
    else
        echo "SPHEX_DIR not found: \"$SPHEX_DIR\"."
        exit 1
    fi

# Find data dir
else
    if [ "$_sub_cmd" == "init" ]; then
        DATA_DIR="$(pwd)/.spx"
    else
        DATA_DIR=$(find_data_dir)
        if [ -z "$DATA_DIR" ]; then
            echo "No repository found. Use \"$PGM_BIN init\""
            exit 1
        fi
    fi
fi


# Check to see if sub-command is in path
_sub_bin="$PGM_BIN-$_sub_cmd"
_fullpath_sub_bin=$(which "$_sub_bin" 2> /dev/null)
if [ $? -ne 0 ]; then
    # else .. Look at the location where this command is
    _fullpath_sub_bin="$INSTALL_DIR/$_sub_bin"
    if [ ! -x "$_fullpath_sub_bin" ]; then
        echo "Invalid command $_fullpath_sub_bin."
        exit 1
    fi
fi


# Execute command
(
export INSTALL_DIR
export DATA_DIR
$_fullpath_sub_bin "$@"
)
