#!/bin/bash
usage() {
    echo "usage: $PGM_BIN cat-file <object> [--output=<file>]"
}

if [ -z "$1" ]; then
    usage
    exit 0
fi

while (( "$#" )); do
    case "$1" in
        -o)
            if [ -z "$2" ]; then
                echo "No output file specified."
                exit 1
            else
                _out_file=$2
                shift 2
            fi
            ;;
        --output=*)
            _out_file=${1#*=}
            shift
            ;;

        -*|--*=)
            echo "Unsupported flag $1." >&2
            exit 1
            ;;

        *)
            _params="$_params $1"
            shift
            ;;
    esac
done

eval set -- "$_params"

if [[ -z "$1" || -n "$2" ]]; then
    usage
    exit 1
fi

_object="$DATA_DIR/objects/${1:0:2}/${1:2}"
if [ ! -r "$_object" ]; then
    echo "Object \"$_object\" not readable."
    exit 1
fi

_blob=$(mktemp /tmp/$PGM_BIN-cat-file.XXXXXX)

zcat "$_object" > "$_blob"
IFS= read -r -d '' _header < "$_blob"

if [ "${_header:0:4}" != "blob" ]; then
    echo "Corrupt object file, invalid signature."
    exit 1
fi

_header_len=$(( ${#_header} + 1 ))
_expected_size=$(( $_header_len + ${_header:5} ))
_size=$(stat --format %s "$_blob")

if [ $_size -ne $_expected_size ]; then
    echo "Corrupt object file, size missmatch."
    exit 1
fi

_file_start=$(( $_header_len + 1 ))
if [ -n "$_out_file" ]; then
    tail -c +$_file_start "$_blob" > "$_out_file"
else
    tail -c +$_file_start "$_blob"
fi

rm "$_blob"
