#!/bin/bash
. "$INSTALL_DIR/spx-core"

usage() {
    echo "usage: $PGM_BIN hash-file [--write] <in file>"
}

if [ -z "$1" ]; then
    usage
    exit 0
fi

while (( "$#" )); do
    case "$1" in
        -w|--write)
            _write=true
            shift
            ;;

        -*|--*=)
            echo "Unsupported flag $1." >&2
            exit 1
            ;;

        *)
            if [ -z "$_file" ]; then
                _file=$1
                shift
            else
                echo "Extra argument \"$1\"" >&2
                exit 1
            fi
            ;;
    esac
done

if [ ! -r "$_file" ]; then
    echo "File \"$_file\" not readable." >&2
    exit 1
fi

_size=$(stat --format %s "$_file")
_blob=$(mktemp "/tmp/$PGM_BIN-hash-file.XXXXXX")

(printf 'blob %s\0' "$_size" && cat "$_file") | gzip > "$_blob"
_sha=$(sha1sum "$_blob" | sed -e 's/ .*//')

if [ -z "$_write" ]; then
    rm "$_blob"
else
    mkdir -p "$DATA_DIR/objects/${_sha:0:2}"
    mv "$_blob" "$DATA_DIR/objects/${_sha:0:2}/${_sha:2}"
fi

echo "$_sha"
