#!/bin/bash
XIT=xit
XIT_VERSION=0.1.2

# TODO(jfrias): determine dir
XIT_DIR=.xit

# No command found
if [ -z "$1" ]; then
    echo "usage $XIT [--version] <command> [<args>]"
    exit 0
fi

while (( "$#" )); do
    case "$1" in
        -v|--version)
            echo "$XIT version $XIT_VERSION"
            exit 0
            ;;
        *)
            _params="$_params $1"
            shift
            ;;
    esac
done

eval set -- "$_params"

# Look in the current directory
_cwd=$(pwd)
if [ -x "$_cwd/$XIT-$1" ]; then
    cmd="$_cwd/$XIT-$1"

# Look in the parth
else
    cmd=$(which "$XIT-$1" 2> /dev/null)
    if [[ $? -ne 0 || ! -x "$cmd" ]]; then
        echo "Invalid command $1."
        exit 1
    fi
fi

# Execute command
shift
(
export XIT
export XIT_DIR
$cmd $*
)
