#!/bin/bash
usage() {
    echo "usage: xit hash-file [-w] <in file>"
}

if [ -z "$1" ]; then
    usage
    exit 0
fi

while (( "$#" )); do
    case "$1" in
        -w|--write)
            _write=true
            shift
            ;;

        -*|--*=)
            echo "Unsupported flag $1." >&2
            exit 1
            ;;

        *)
            _params="$_params $1"
            shift
            ;;
    esac
done

eval set -- "$_params"

if [[ -z "$1" || -n "$2" ]]; then
    usage
    exit 1
fi

_file=$1

if [ ! -r "$_file" ]; then
    echo "File \"$_file\" not readable."
    exit 1
fi

_size=$(stat --format %s "$_file")
_blob=$(mktemp /tmp/xit-hash-file.XXXXXX)

(printf 'blob %s\0' "$_size" && cat "$_file") | gzip > "$_blob"
_sha=$(sha1sum "$_blob" | sed -e 's/ .*//')

if [ -z "$_write" ]; then
    rm "$_blob"
else
    mkdir -p "$XIT_DIR/objects/${_sha:0:2}"
    mv "$_blob" "$XIT_DIR/objects/${_sha:0:2}/${_sha:2}"
fi

echo "$_sha"
